[package]
name = "ltrait-ui-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
ltrait = "0.7.0"

crossterm = { version = "0.28.1", features = ["event-stream"] }
ratatui = "0.29.0"
tui-input = "0.11.1"

tokio = { version = "1.44.0", features = ["full"] }
futures-lite = "2.6.0"
futures = "0.3.31"
rustc-hash = "2.1.1"
