[package]
name = "ltrait-ui-tui"
version = "0.1.0"
edition = "2024"

[package.metadata.typos.default.extend-words]
ratatui = "ratatui"

[dependencies]
ltrait = "0.9.0"

crossterm = { version = "0.28.1", features = ["event-stream"] }
ratatui = "0.29.0"
tui-input = "0.11.1"

futures = "0.3.31"
tokio = { version = "1.44.1", features = [
  "rt",
  "sync",
  "time",
], default-features = false }
tracing = "0.1.41"
