[workspace]

members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["satler <satler@satler.dev>"]
edition = "2024"
license = "MIT"
repository = "https://github.com/ltrait/exts"
rust-version = "1.88.0"
exclude = [".envrc"]

[workspace.dependencies]
ltrait = "1.1.1"
