[package]
name = "ltrait-source-desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
ltrait = { git = "https://github.com/ltrait/ltrait" }

freedesktop-icons = "0.3.1"
freedesktop-desktop-entry = "0.7.8"
base64 = "0.22.1"
image = "0.25.5"

thiserror = "2.0.12"
