[package]
name = "ltrait-sorter-frency"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
dirs = "6.0.0"
ltrait = "0.4.0"
rusqlite = { version = "0.34.0", features = ["chrono", "bundled"] }
